### DISCUSSION TITLE
Reserved ports: 80 and 443 by router

### DISCUSSION THREAD

**Discussion by shawnthompson** [htpcBeginner/docker-traefik#181] [Support]
So I've had this docker setup for quite sometime now and running smoothly. Thanks again!

But I went and bought an ASUS ZenWiFi AX mesh router which hogs the ports 80 and 443 for their UI.

I also setup their DDNS service with gives me a _DOMAIN_.asuscomm.com domain. I'm not sure this will work because of the subdomain they are giving me. Can I use sonar._domain_.asuscomm.com?

I am using Cloud Flare and Cloudflare-Companion. What would I do in CloudFlare if I'm using a domain instead of an IP? 

What should do I change in the `docker-compose-t2.yml` file to access Traefik via the browser? I tried changing the ports and I still couldn't access it.

Maybe I'll redo the guide from scratch... if I find the time.

**Comment by shawnthompson** [comment]
@htpcBeginner can I change the endpoints for Traefix?

```
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
```

I'd rather see if I can change these isn't of trying to the port for the UI for the router.
