### DISCUSSION TITLE
Cloudflare companion secret not working

### DISCUSSION THREAD

**Discussion by oltronix** [htpcBeginner/docker-traefik#184] [Show and tell]
Don't know if this is the right place, but since I've had so much help from this guide I just wanted to point out a fix for this comment in the cloudflare companion section. 

```
  # Cloudflare-Companion - Automatic CNAME DNS Creation
  cf-companion:
    container_name: cf-companion
    image: tiredofit/traefik-cloudflare-companion:latest
   ...
    secrets: # not working
      - cloudflare_api_token
```

[If you rename the secret as cf_token it works.](https://github.com/tiredofit/docker-traefik-cloudflare-companion#docker-secrets) You can then remove the environment variables and just specify the secret like so:

```
    environment:
      - TIMEZONE=$TZ
      - TRAEFIK_VERSION=2
      - TARGET_DOMAIN=$DOMAINNAME
      - DOMAIN1=$DOMAINNAME
      - DOMAIN1_ZONE_ID=$CLOUDFLARE_ZONE # Copy from Cloudflare Overview page
      - DOMAIN1_PROXIED=TRUE
      - DOCKER_HOST=tcp://socket-proxy:2375
    secrets: # now working :)
      - cf_token
```

edit: Removed the email as the api_token + email does not work it only needs a api token with dns zone permission.

edit2: 
I've been trying to remove all secrets from my .env so that i can have it in my repo. Also got the secret file working for the forward auth

Putting the following into a secret file
```
providers.google.client-id={id}.apps.googleusercontent.com
providers.google.client-secret={client-secret}
secret={secret}
```

Then adding a secret to the docker compose:
```
secrets:
  traefik-forward-auth:
    file: $DOCKERDIR/secrets/traefik-forward-auth
```

And then in the oauth service
```
  secrets:
      - source: traefik-forward-auth
        target: /config
    environment:
      - CONFIG=/config
      - COOKIE_DOMAIN=$DOMAINNAME
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAINNAME
      - URL_PATH=/_oauth
      - WHITELIST=$MY_EMAIL
      - LOG_LEVEL=warn
      - LOG_FORMAT=text
      - LIFETIME=2592000 # 30 days
```
