### DISCUSSION TITLE
issues with Odoo install

### DISCUSSION THREAD

**Discussion by 0x9c7d0d94** [htpcBeginner/docker-traefik#248] [Q&A]
Hi there, I am fairly new to using docker and this repo has been really useful.
I have managed to setup the basic server and installed a few apps for monitoring/usability and I am super happy so far, however I am failing to get a few applications working... I am sure that it is something I am missing/doing incorrect.
the snippet from the .yml file looks like this (networks, traefik etc set up similar/exact to the repo here)

```
########################## Odoo
# odoo
  odoo:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: odoo:15
    container_name: odoo
    depends_on:
      - odoo-db
    volumes:
      - $USERDIR/odoo/web-data:/var/lib/odoo
      - $USERDIR/odoo/config:/etc/odoo
      - $USERDIR/odoo/addons:/mnt/extra-addons
      - $USERDIR/odoo/logs:/var/log/odoo
    networks:
      - t2_proxy
      - socket_proxy
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD_FILE=/run/secrets/odoo_db_password
    secrets:
      - odoo_db_password
    labels:
       - "traefik.enable=true"
    #   ## HTTP Routers
       - "traefik.http.routers.odoo-rtr.entrypoints=https"
       - "traefik.http.routers.odoo-rtr.rule=Host(`odoo.$DOMAINNAME0`)"
    #   ## Middlewares
       - "traefik.http.routers.odoo-rtr.middlewares=chain-no-auth@file"
    #   ## HTTP Services
       - "traefik.http.routers.odoo-rtr.service=odoo-svc"
       - "traefik.http.services.odoo-svc.loadbalancer.server.port=8069"
    
# odoo db
  odoo-db:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: postgres:13
    container_name: odoo-db
    networks:
      - t2_proxy
      - socket_proxy
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/odoo_db_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - $USERDIR/odoo/db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - odoo_db_password
```

The above config minus the traefik/proxy network works fine in a separate stack but I am struggling to get the traefik elements to work with it. Any help would be appreciated as I have been stuck on this for a couple of days now :(
I get a Error 502 when trying to view the page.

Edit: I have tried changing the ports on the loadbalancer, as well as specifying them in the odoo config 8069:8069, 8069:80 etc.

**Comment by beefstew809** [comment]
I ended up using the bitnami images and traefik worked for me. I know that doesn't really answer your question but it is at least an option.

```
  odoo:
    image: docker.io/bitnami/odoo:15
    container_name: odoo
    networks:
      - t2_proxy
      - socket_proxy
    # ports:
    #   - '8069:8069'
    volumes:
      - $DOCKERDIR/odoo/odoo_data:/bitnami/odoo
    depends_on:
      - postgresql-oodo
    environment:
      - ODOO_DATABASE_HOST=postgresql-odoo
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
      - ODOO_DATABASE_PASSWORD=$ODOODBPASS
      - ODOO_EMAIL=$MY_EMAIL
      - ODOO_PASSWORD=$ODOOPASS
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.odoo-web-rtr.entrypoints=https"
      - "traefik.http.routers.odoo-web-rtr.rule=Host(`odoo.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.odoo-web-rtr.middlewares=chain-authelia@file"
      #- "traefik.http.routers.odoo-web-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.odoo-web-rtr.service=odoo-web-svc"
      - "traefik.http.services.odoo-web-svc.loadbalancer.server.port=8069"

  postgresql-odoo:
    image: docker.io/bitnami/postgresql:13
    container_name: postgresql-odoo
    volumes:
      - $DOCKERDIR/odoodb/postgresql_data:/bitnami/postgresql
    networks:
      - t2_proxy
      - socket_proxy
    environment:
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
      - POSTGRESQL_PASSWORD=$ODOODBPASS
```
