### DISCUSSION TITLE
HomeAssistant Behind Traefik

### DISCUSSION THREAD

**Discussion by Blehhh** [htpcBeginner/docker-traefik#259] [Q&A] [answered]
I have been trying to get HA operating in `network_mode: Host` working behind Traefik and have been having no luck, my initial setup is based off the [Traefikv2](https://www.smarthomebeginner.com/traefik-2-docker-tutorial/) guide, everything else I have gotten to work fine but am a bit stumped on this one. I have tried creating a homeassistant.toml file in the traefik/rules folder but I just get a 400: Bad Request. Any help appreciated.

docker compose homeassistant:

```
homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - $DOCKERDIR/docker/homeassistant:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    ports:
    - "8123:8123"
```

homeassistant.toml file:

```
[http.routers]
  [http.routers.homeassistant-rtr]
      entryPoints = ["https"]
      rule = "Host(`homeassistant.example.com`)"
      service = "homeassistant-svc"
      middlewares = ["chain-authelia"]
      [http.routers.homeassistant-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.homeassistant-svc]
  [http.services.homeassistant-svc.loadBalancer]
	passHostHeader = true
      [[http.services.homeassistant-svc.loadBalancer.servers]]
	  url = "http://SERVER_PRIVATE_IP:8123" # or whatever your external host's IP:port is

```

**Comment by danielfmo** [comment, marked as answer]
Check your home assistant logs. 
It is most probably complaining about not trusted proxy. 

If that's the case you'll neeed to add to the configuration.yaml (of home assistant) something like:
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "SERVER_PRIVATE_IP"
```

**Reply by Blehhh** [reply]
this was the fix thank you so much, though instead of using my servers IP address I had to use my traefik IP address in the configuration.yaml so it looked like:

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "TRAEFIK_IP"
```
