### DISCUSSION TITLE
Youtube-DL-Material

### DISCUSSION THREAD

**Discussion by robflate** [htpcBeginner/docker-traefik#260] [Show and tell]
Regarding the latest commit 6c917d6e45a35da4c59b1f466b27c9d42dd297de and Youtube-DL-Material not working. I have a stack heavily based on yours and the following works;

```
###############################################################################
# YouTubeDL Material - Material Design frontend for youtube-dl
# https://hub.docker.com/r/tzahi12345/youtubedl-material
#
# notes: Works
###############################################################################
  youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - "$YOUTUBEDLMATERIAL_PORT:17442"
    volumes:
      - $CONFIG/youtubedl-material/appdata:/app/appdata
      - $DATA/direct/youtubedl-material/audio:/app/audio
      - $DATA/direct/youtubedl-material/video:/app/video
      - $DATA/direct/youtubedl-material/subscriptions:/app/subscriptions
      - $DATA/direct/youtubedl-material/users:/app/users
    environment:
      UID: $PUID
      GID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.youtubedl-material-rtr.entrypoints=https"
      - "traefik.http.routers.youtubedl-material-rtr.rule=Host(`youtubedl-material.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.youtubedl-material-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.youtubedl-material-rtr.service=youtubedl-material-svc"
      - "traefik.http.services.youtubedl-material-svc.loadbalancer.server.port=17442"
```
