### DISCUSSION TITLE
Log monitoring and alerts

### DISCUSSION THREAD

**Discussion by SimpleHomelab** [htpcBeginner/docker-traefik#262] [Ideas]
I am new to the topic of log monitoring. I would like to add something simple to do the following:

1. Check the logs (from various sources) for specific phrases or events
2. If found, send a notification (Telegram, email, etc.)

Does anyone know of something that can do this. I have read around and there is Graylog, Grafana/Loki, etc. Just wondering if there is simpler and opensource/free for homelab use.

EDIT1: Since i already have grafana in the stack, I am wondering if I should just build on it and add Loki and eventually Prometheus for monitoring needs.

Sorry, just looping in few frequent visitors here: @robflate @DennisGaida @shawnthompson @uasdj25 @gzecchi

**Comment by robflate** [comment]
It’s something I keep meaning to do but never get round to. For 95% of the issues I have, Dozzle & Portainer help me find the problem. Interested in a more complete solution though.

**Comment by DennisGaida** [comment]
Thanks for looping me in! I'll just put my `elasticsearch-stack` branch here, which I set up alright, but I tore it down again because in my experience it was freaking slow / lots of resource usage. I have heard that `logstash` would be what you are asking, but again: I didn't get it running smoothly and easily. Startup was like 30s-60s.

Without further ado (mind you I am using a cleaner named `traefik_proxy` network name and some other variable names such as $DOCKERDIR or $DOMAIN_INTERNAL [instead of that nondescriptive DOMAIN0], besides that everything should work just like in your config):
```
  # ELK - Stack
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.3
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/elasticsearch:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - default
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ports:
    #   - 9200:9200
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "elasticsearch"

  logstash:
    container_name: logstash
    image: logstash:7.16.3
    restart: unless-stopped
    # links:
    #   - elasticsearch
    volumes:
      - $DOCKERDIR/logstash:/etc/logstash
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    command: logstash -f /etc/logstash/logstash.conf
    networks:
      - traefik_proxy
      - default
    ports:
      - 12201:12201/udp
    # depends_on:
    #   - elasticsearch
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "logstash"

  kibana:
    container_name: kibana
    image: kibana:7.16.3
    restart: unless-stopped
    networks:
      - traefik_proxy
      - default
    # ports:
    #   - 5601:5601
    # depends_on:
    #   - elasticsearch
    #   - logstash
    #   - traefik
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.kibana-rtr.entrypoints: "https"
      traefik.http.routers.kibana-rtr.rule: "Host(`kibana.${DOMAIN_INTERNAL}`)"
      ## Middlewares
      traefik.http.routers.kibana-rtr.middlewares: "chain-authelia@file"
      ## HTTP Services
      traefik.http.routers.kibana-rtr.service: "kibana-svc"
      traefik.http.services.kibana-svc.loadbalancer.server.port: "5601"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "kibana"
```

As for Prometheus - yes I have that running and use it quite heavily. I'm using Prometheus with quite a few services: `matusnovak/prometheus-smartctl`,  `prom/blackbox-exporter`, `miguelndecarvalho/speedtest-exporter`, `netdata/netdata`. Especially netdata is insane in the amount of information you get. Also a resource hog. I haven't played with log ingestion yet for Prometheus and now you set me on another path :)

```
  # Prometheus - monitoring and alerting toolkit
  # https://github.com/prometheus/prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    <<: *common-keys-unstopped
    networks:
      - traefik_proxy
      - default
    user: ${PUID}:${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $DOCKERDIR/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $DOCKERDIR/prometheus/data:/prometheus # TODO: Storage policies
    # to enable web admin api:
    # command: [ "--web.enable-admin-api",
    #          "--config.file=/etc/prometheus/prometheus.yml",
    #          "--storage.tsdb.path=/prometheus",
    #          "--web.console.libraries=/usr/share/prometheus/console_libraries",
    #          "--web.console.templates=/usr/share/prometheus/consoles" ]
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.prometheus-rtr.entrypoints: "https"
      traefik.http.routers.prometheus-rtr.rule: "Host(`prometheus.${DOMAIN_INTERNAL}`)"
      ## Middlewares
      traefik.http.routers.prometheus-rtr.middlewares: "chain-authelia@file"
      ## HTTP Services
      traefik.http.routers.prometheus-rtr.service: "prometheus-svc"
      traefik.http.services.prometheus-svc.loadbalancer.server.port: "9090"
```

As far as "figure out where a problem comes from", logs is one thing and I usually just check those logs first. I would love to do end-to-end request tracing and thought that Jaeger for Traefik would be nice, but that was very complicated to set up and I couldn't get it working easily https://traefik.io/blog/application-request-tracing-with-traefik-and-jaeger-on-kubernetes/.
