### DISCUSSION TITLE
Unifi Rule Resulting in 404 for all Services

### DISCUSSION THREAD

**Discussion by vmcosco** [htpcBeginner/docker-traefik#263] [Q&A] [answered]
I am trying to get Unifi set up as an external service.  I created the rule using the example in the repo.  It the rule is not immediately loaded and if I restart Traefik, I get 404 errors for Traefik and all services.  The log entry thar indicates the issue seems to be:

`msg="Cannot start the provider *file.Provider: /rules/app-unifi.yml: field not found, node: address"`

That resulted in no other rules being loaded.

Below is my app-unifi.yml file.  Any issues? The file permissions match my Emby and Home Assistant rules that work fine.

```
http:
  routers:
    unifi-rtr:
      rule: "Host(`unifi.mydomain.net`)"
      entryPoints:
        - https
      middlewares:
        - chain-no-auth
      service: unifi-svc
      tls:
        certResolver: dns-cloudflare
  services:
    unifi-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - address: "https://192.168.1.20:8443"
```
