### DISCUSSION TITLE
Traefik log message about Compression: "mime: no media type"

### DISCUSSION THREAD

**Discussion by mcmaxl** [htpcBeginner/docker-traefik#325] [Q&A]
Hi all,

I have setup Traefik according to Anands latest guide on his blog and its working fine, however I am seeing lots of these log entries:

```
level=debugmiddlewareName=middlewares-compress@filemiddlewareType=Compressmsg=mime: no media typetime=2024-03-16T21:19:46+01:00
```

can this just be ignored or is something likely to be wrong with my setup? I couldnt find any related discussions.

Thanks in advance!

**Comment by xenion1987** [comment]
Same here using Traefik 3.3.3

```yaml
---
http:
  middlewares:
    gzip:
      compress: {}

```

```log
traefik  | 2025-02-19T15:08:21.610600828Z 2025-02-19T16:08:21+01:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/compress/compress.go:127 > Unable to parse MIME type error="mime: no media type" middlewareName=gzip@file middlewareType=Compress
```

**Reply by mkarg** [reply]
Same here, Traefik 3.4

**Comment by noadc-dev** [comment]
Did either of you ever figure this out?  I'm having the same error with Traefik v3.3.4

I tried turning off compression for various filetypes, but still get the error.

```
http:
  middlewares:
        gzip:
        compress:
          excludedContentTypes:
            - "image/png"
            - "image/jpeg"
            - "image/gif"
            - "video/mp4"
            - "audio/mpeg"
            - "application/zip"
            - "application/pdf"
            - "application/x-tar" 
```

```
2025-02-26T09:26:14-05:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/compress/compress.go:127 > Unable to parse MIME type error="mime: no media type" middlewareName=gzip@file middlewareType=Compress
```
`
