### DISCUSSION TITLE
mellow - discord bot to add movies / tv to ombi/sonarr/radarr

### DISCUSSION THREAD

**Discussion by tombomb** [htpcBeginner/docker-traefik#45] [Ideas]
Just thought i would throw this here if people had not heard of it, feel free to close / delete this issue if you want.  I don't let my less technical family members access the web apps but it gets tiring when they ask for stuff. I was going to make my own bot but found that someone had already did it, it works well with the stack, just have to add a bypass to the tautulli api, but thats 2 seconds of copy / paste

**Comment by tombomb** [comment]
```
  mellow:
    image: voidp/mellow:latest
    container_name: mellow
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - "9005:5060"
    volumes:
      - $USERDIR/docker/mellow:/usr/src/app/data
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.mellow-rtr.entrypoints=https"
      - "traefik.http.routers.mellow-rtr.rule=Host(`mellow.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.mellow-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.mellow-rtr.service=mellow-svc"
      - "traefik.http.services.mellow-svc.loadbalancer.server.port=5060"
```
