### ISSUE TITLE
PMA and Mariadb not playing nice

### ISSUE THREAD

**Issue by pittbull** [htpcBeginner/docker-traefik#148]
Hi,

and thank you ever so much for taking the time to compile your experience and knowledge into these guides. I've been running docker for awhile but with your guides I am able to be more confident in that my setup is secure, and learning a few things here and there. :)

I do seem to have done something wrong because I am not able to get mariadb and phpmyadmin to play together.

I have successfully setup organizr, and authelia and both are working perfectly. When I replicate the setup for Mariadb and pma they both start and I am able to login (via Authelia) and get the pma login screen.

When trying to login with root the browser hangs for nearly a minute before doing anything, and eventually I get the pma admin screen. The slowness is still present though when trying to click around in the gui and this leads me to think that something is not correct. (I am waiting between 20-60 seconds if I click around the various tabs in pma) I have also tried to create a new admin user without any noticeable effect.

When starting pma I see the following in my log:

```
phpmyadmin    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message
phpmyadmin    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message
```

And these are my docker-compose sections:

  ```
# phpMyAdmin - Database management
  # Create a new user with admin privileges. Cannot login as MySQL root for some reason.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      - t2_proxy
      - default
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "$PMA_PORT:80"
    # volumes:
    #   - $DOCKERDIR/appdata/phpmyadmin:/etc/phpmyadmin
    environment:
      - PMA_HOST=$MARIADB_HOST
      - PMA_PORT=$MARIADB_PORT
      #- PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`pma.$DOMAINNAME`)"
      - "traefik.http.routers.phpmyadmin-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
```

```
# MariaDB - MySQL Database
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    restart: always
#    networks:
#      - t2_proxy:
#          ipv4_address: 192.168.90.250
    security_opt:
      - no-new-privileges:true
    ports:
      - "3306:3306"
    volumes:
      - $DOCKERDIR/mariadb/data:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
```

What have I missed?
