### ISSUE TITLE
Authelia Misdirected Request

### ISSUE THREAD

**Issue by lastcatbender** [htpcBeginner/docker-traefik#167]
Thanks you for amazing guide, it helped me a lot.  But I do have a problem.

When I want to access a page or any domain (e.g. whoami.mydomain.com) on windows computer, authelia works fine.
But when I try to do it on my iphone (safari or chrome) it just gives me "**Misdirected Request**" error. It also happens on google oauth too.
It seems like it happens only on internal network. I don't know why i happens on my mobile. Sometimes I can access authelia.mydomain.com but not subdomains.

### Authelia logs:
```json
time="2021-05-07T02:57:27+03:00" level=info msg="Access to https://whoami.mydomain.com/ (method GET) is not authorized to user <anonymous>, redirecting to https://authelia.mydomain.com?rd=https%3A%2F%2Fwhoami.mydomain.com%2F&rm=GET" method=GET path=/api/verify remote_ip=192.168.5.1
```

### Traefik logs:
```json
today at 2:57:50 AM  time="2021-05-07T02:57:50+03:00" level=debug msg="TLS options difference: SNI=tls-opts@file, Header:default" req.TLS.ServerName=whoami.mydomain.com host=authelia.mydomain.com req.Host=authelia.mydomain.com
today at 2:57:51 AM  time="2021-05-07T02:57:51+03:00" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://authelia.mydomain.com. StatusCode: 302" middlewareType=ForwardedAuthType middlewareName=middlewares-authelia@file
today at 2:57:51 AM  time="2021-05-07T02:57:51+03:00" level=debug msg="TLS options difference: SNI=tls-opts@file, Header:default" req.Host=authelia.mydomain.com req.TLS.ServerName=whoami.mydomain.com host=authelia.mydomain.com
today at 2:57:52 AM  time="2021-05-07T02:57:52+03:00" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://authelia.mydomain.com. StatusCode: 302" middlewareName=middlewares-authelia@file middlewareType=ForwardedAuthType
today at 2:57:52 AM  time="2021-05-07T02:57:52+03:00" level=debug msg="TLS options difference: SNI=tls-opts@file, Header:default" req.Host=authelia.mydomain.com req.TLS.ServerName=whoami.mydomain.com host=authelia.mydomain.com
```
### Traefik2 docker-compose
```yml
  # Traefik 2 - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:v2.4 # chevrotin # the chevrotin tag refers to v2.2.x
    restart: always
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entryPoints.ssh.address=:2222
      ## Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      # - --entryPoints.ping.address=:8081
      - --api=true
      # - --api.insecure=true
      - --api.dashboard=true
      #- --ping=true
      - --pilot.token=$TRAEFIK_PILOT_TOKEN
      #- --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=debug # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      # - --providers.docker.endpoint=unix:///var/run/docker.sock # Use Docker Socket Proxy instead for improved security
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      # Automatically set Host rule for services
      # - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME0`)
      - --providers.docker.exposedByDefault=false
      # - --entrypoints.https.http.middlewares=chain-oauth@file
      - --entrypoints.https.http.tls.options=tls-opts@file
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME0
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME0
      # - --entrypoints.https.http.tls.domains[1].main=$DOMAINNAME1 # Pulls main cert for second domain
      # - --entrypoints.https.http.tls.domains[1].sans=*.$DOMAINNAME1 # Pulls wildcard cert for second domain
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory
      # - --providers.file.filename=/path/to/file # Load dynamic configuration from a file
      - --providers.file.watch=true # Only works on top level files in the rules folder
      # - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90 # To delay DNS check and reduce LE hitrate
    networks:
      t2_proxy:
        ipv4_address: 192.168.4.254 # You can specify a static IP
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    #healthcheck:
    #  test: ["CMD", "traefik", "healthcheck", "--ping"]
    #  interval: 5s
    #  retries: 3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      # - target: 8080
      #   published: 8080
      #   protocol: tcp
      #   mode: host
      # - target: 2222
      #   published: 2222
      #   protocol: tcp
      #   mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/traefik2/rules:/rules # file provider directory
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
      - $DOCKERDIR/appdata/traefik2/acme/acme.json:/acme.json # cert location - you must touch this file and change permissions to 600
      - $DOCKERDIR/appdata/traefik2/traefik.log:/traefik.log # for fail2ban - make sure to touch file before starting container
      - $DOCKERDIR/shared:/shared
      #- $DOCKERDIR/appdata/traefik2/traefik.toml:/etc/traefik/traefik.toml #static config location
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
      - HTPASSWD_FILE=/run/secrets/htpasswd # HTPASSWD_FILE can be whatever as it is not used/called anywhere.
    secrets:
      - cloudflare_email
      - cloudflare_api_key
      - htpasswd
    labels:
      #- "autoheal=true"
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME0`)"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Healthcheck/ping
      #- "traefik.http.routers.ping.rule=Host(`traefik.$DOMAINNAME0`) && Path(`/ping`)"
      #- "traefik.http.routers.ping.tls=true"
      #- "traefik.http.routers.ping.service=ping@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file"
```

### Authelia docker-compose
```yml
  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  # https://www.smarthomebeginner.com/docker-authelia-tutorial/
  authelia:
    container_name: authelia
    # Check this before upgrading: https://github.com/authelia/authelia/blob/master/BREAKING.md
    image: authelia/authelia:latest
    restart: always
    logging:
      driver: json-file
    networks:
      - t2_proxy
      - default
    ports:
      - "9091:9091"
    depends_on:
      - traefik
      - mariadb
      # - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/authelia:/config
    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME0`)"
      - "traefik.http.routers.authelia-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      # - "traefik.http.routers.authelia-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
```
### whoami (for test purposes)
```yml
  whoami:
    container_name: whoami
    image: containous/whoami
    restart: always
    networks:
    - t2_proxy
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whoami-rtr.entrypoints=https"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.$DOMAINNAME0`)"
      ## Middlewares
      # - "traefik.http.routers.whoami-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.whoami-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
 ```
### Authelia configuration
```yml
###############################################################
#                   Authelia configuration                    #
###############################################################
# https://www.smarthomebeginner.com/docker-authelia-tutorial/

host: 0.0.0.0
port: 9091
log_level: debug # When creating bypass rules or troubleshooting, you may change the log_level to debug, trace, or info.

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# I used this site to generate the secret: https://www.grc.com/passwords.htm
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.mydomain.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 512 # blocks this much of the RAM. Tune this. # DEF:1024

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.mydomain.com
      policy: bypass
#    - domain: radarr.example.com
#      policy: bypass
#      subject: "group:admins"
#      resources:
#      - "^/api/.*$"
#    - domain: "*.example.com"
#      policy: one_factor
    - domain: "*.mydomain.com"
      policy: two_factor
    - domain: "mydomain.com"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: mydomain.com # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
#  redis:
#    host: redis
#    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
# For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
#  local:
#    path: /config/db.sqlite3
  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
    host: mariadb
    port: 3306
    database: authelia
    username: redacted
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    # password: use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE

notifier:
   smtp:
     username: redacted@gmail.com
     # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
     # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
     host: smtp.gmail.com
     port: 587 #465
     sender: redacted@gmail.com
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  #filesystem:
  #  filename: /config/notification.txt # /tmp/authelia/notification.txt

  whoami:
    container_name: whoami
    image: containous/whoami
    restart: always
    networks:
    - t2_proxy
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whoami-rtr.entrypoints=https"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.$DOMAINNAME0`)"
      ## Middlewares
      # - "traefik.http.routers.whoami-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.whoami-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
```
Running on synology ds920+ on docker. I don't think this helps much though.

I'm open to any kind of feedback/help. Please, I'm about to go crazy. I just want to browse my sonarr/radarr on mobile, nothing much nothing less.

**Comment by alexander-t7** [comment]
I have this same issue. Everything works fine on desktop browsers, however when I move to an iOS-based (WebKit) browser, I get the 421 error. I have not figured out the root cause of the issue, but I could make it work by deleting the entire cipherSuites section in tls-opts.yml

I’m not too concerned about this, as I only use modern, up-to-date browsers that support TLS 1.3 thus I’ve also changed the Traefik’s minimum TLS version to 1.3 in tls-opts.yml (minVersion: VersionTLS12)

**Comment by jarrah31** [comment]
I too keep getting Misdirected Requests 421 errors, but it's untreated to Authelia as I'm using OAuth. 
It's something to so with Safari being more sensitive with different sub-domains and TLS certs. 

I think it's related to Domain Fronting, but not sure how to address it. 
"In the case of domain fronting, if the TLS options associated with the Host Header and the SNI are different then Traefik will respond with a status code 421." - https://doc.traefik.io/traefik/routing/routers/ 

https://serverfault.com/questions/916724/421-misdirected-request

I can never figure out why it keeps happening. :(

**Comment by jarrah31** [comment]
OMG, I've figured it out at long last!!!! 

I turned on Traefik debug logging and after saving a change on one of the files, I noticed the following in the logs:

```
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for tasmoadmin.domain.com with TLS options default" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for portainer.domain.com with TLS options default" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for grafana.domain.com with TLS options default" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for srv2.domain.com with TLS options default" entryPointName=https
*today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for tautulli.domain.com with TLS options tls-opts@file" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for srv1.domain.com with TLS options default" entryPointName=https
*today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for ss.domain.com with TLS options tls-opts@file" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for oauth.domain.com with TLS options default" entryPointName=https
*today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for plex.domain.com with TLS options tls-opts@file" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for s3.domain.com with TLS options tls-opts@file" entryPointName=https
*today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for guac.domain.com with TLS options tls-opts@file" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for z2m2.domain.com with TLS options default" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for srv3.domain.com with TLS options default" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for octoprint.domain.com with TLS options default" entryPointName=https
*today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for traefik.domain.com with TLS options tls-opts@file" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for z2m3.domain.com with TLS options default" entryPointName=https
today at 19:46:26 time="2021-09-28T18:46:26Z" level=debug msg="Adding route for logs.domain.com with TLS options default" entryPointName=https```

I noticed that some entries said "with TLS options default" and some said "with TLS options tls-opts@file"

I systematically tested each entry and made a * next to the ones that failed with Misdirected Requests, and there was a 1-2-1 match with those that contained "with TLS options tls-opts@file".

Looking that my docker-compose file I compared a working set of labels to a container that wasn't working:

Working:
```
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)"
      - "traefik.http.routers.portainer-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
```

Not working:
```
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefox-rtr.entrypoints=https"
      - "traefik.http.routers.firefox-rtr.rule=Host(`firefox.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.firefox-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.firefox-rtr.service=firefox-svc"
      - "traefik.http.services.firefox-svc.loadbalancer.server.port=5800"
```

I noticed the following line was missing from the broken container!
```
- "traefik.http.routers.portainer-rtr.tls=true"
```

Even my Traefik entry wasn't working because it was missing this line. 

**I added the tls=true line to all containers that were missing this label (changing the router name to match), and Eureka, no more Misdirected Request errors!** 

I'm so happy this is finally solved, it's been happening for over a year now. The error was random, it would sometimes work fine on these domains and sometimes it wouldn't. I suspect it was due to how often I'd use a particular service, maybe it worked if I hadn't accessed any internal services for a few days, maybe it worked after I restarted something. 

Interestingly, looking at @htpcBeginner docker compose file (https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml), all of the docker containers (except OAuth and authelia) don't have this entry, so I need to look into why that is...

**Comment by jarrah31** [comment]
Ok then, I see that on the main guide For Traefik 2 (https://www.smarthomebeginner.com/traefik-2-docker-tutorial/) every container example contains the "tls=true" line within " ## HTTP Routers", yet it's missing from the GitHub compose file...

@htpcBeginner do you know why this entry was removed out of interest please?

**Comment by Flute7** [comment]
I have exactly the same 'Misdirected Request' message on Safari as you do. 
The issue only started to occur after I setup NAT Loopback/Host Overrides to prevent my authentication requests leaving WAN when accessing from local network. Perhaps this is related or simply co-incidence?

As for the "tls=true" line; I believe it was removed due to the inclusion of the tls-opts file that was supposed to apply TLS by default to all services.

See the following line and corresponding note under the traefik service.

      - "--entrypoints.https.http.tls.options=tls-opts@file" # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services.

**Comment by jimmyharris** [comment]
Has anyone been able to determine what is causing this? With the latest iOS I can't access any subdomains behind authelia.

**Comment by jeffbyrnes** [comment]
I ran into this same issue, and commenting out the `tls-opts` command arg:

```yaml
services:
  traefik:
    command:
      - --entrypoints.https.http.tls.options=tls-opts@file
```

was the fix. I’m a total newb to Traefik & this whole setup, so I’m probably missing a piece somewhere, but this did the trick
