### ISSUE TITLE
middlewares-https-redirectscheme is missing from middlewares.yml.example in 2.5 update

### ISSUE THREAD

**Issue by tehniemer** [htpcBeginner/docker-traefik#187]
The middleware for the new redirect scheme in 2.5 is missing from the example.

**Comment by proddy** [comment]
yes I noticed that too. An entry is needed in the `middlewares.yml` file. Without out you'll get errors like

 ```
time="2021-10-04T13:45:50Z" level=error msg="middleware \"middlewares-https-redirectscheme@file\" does not exist" entryPointName=https routerName=dozzle-rtr@docker
```

**Comment by tehniemer** [comment]
This worked for me.

```
    middlewares-https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
```
