### ISSUE TITLE
Warning: No domain found in rule

### ISSUE THREAD

**Issue by marapavelka** [htpcBeginner/docker-traefik#209]
When I look at the Traefik container log, I see a lot of these warnings:
```
time="2022-01-05T16:16:59Z" level=warning msg="No domain found in rule HostRegexp(`{host:.+}`), the TLS options applied for this router will depend on the hostSNI of each request" entryPointName=https routerName=errorpages-rtr@docker
```

This is my errorpages.yml file:
```
version: "3.9"
services:

## Traefik - Custom Error Pages
  traefik-error-pages:
    container_name: errorpages
    hostname: errorpages
    image: guillaumebriday/traefik-custom-error-pages:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.errorpages-rtr.entrypoints=https"
      - "traefik.http.routers.errorpages-rtr.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.errorpages-rtr.priority=1"
      # Middlewares
      - "traefik.http.routers.errorpages-rtr.middlewares=errorpages"
      - "traefik.http.middlewares.errorpages.errors.service=errorpages-svc"
      - "traefik.http.middlewares.errorpages.errors.status=401,403,404,429,500,502,503"
      - "traefik.http.middlewares.errorpages.errors.query=/{status}.html"
      # HTTP Services
      - "traefik.http.routers.errorpages-rtr.service=errorpages-svc"
      - "traefik.http.services.errorpages-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
```
Is there something wrong with it? Or should I ignore these warnings?
