### ISSUE TITLE
Can't get VScode work correctly

### ISSUE THREAD

**Issue by thibaudbrg** [htpcBeginner/docker-traefik#255]
Hello, I'm struggling with adding the VScode docker-compose. I'm following the instructions [here](https://www.smarthomebeginner.com/wordpress-on-docker-traefik/), but there are some sentences that I think I didn't understand correctly. 

The code I use is basically the same as the one in the repo:

  ```
vscode:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: codercom/code-server:latest
    container_name: vscode
    volumes:
      - $USERDIR/server:/home/coder/server
      - $DOCKERDIR:/home/coder/docker
      - $DOCKERDIR/appdata/vscode:/home/coder
    environment:
      PASSWORD: $VSCODE_PASSWORD
      # Run as root first, create the directories, then change permissions to user:docker and 775. Disable run as root below.
      user: $PUID:$PGID
      #user: "0"
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$DOMAINNAME1`)"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8080"
```

So when I'm following these instructions:
![Screenshot 2022-03-06 182711](https://user-images.githubusercontent.com/73235385/156934507-a8bc52f3-7b7d-478f-ae18-f52501629a2a.png)

I suppose during the "tricky" part, I have to do smth like: `sudo chmod -R 775 /volume1/docker/appdata/vscode/` but still, even after restarting the container the logs are:
![Screenshot 2022-03-06 183119](https://user-images.githubusercontent.com/73235385/156934678-5fb7586e-f949-4348-8b04-bf601ba5838a.png)

I don't get what is this folder /home/coder/docker, do I have to manually create it (it doesn't work)? And basically where is the folder home? I only have the folder /volume1/homes/
Do I have to create a folder /home/ in the $DOCKERDIR directory?
