### ISSUE TITLE
Changing app rule from toml to yml

### ISSUE THREAD

**Issue by ahmaddxb** [htpcBeginner/docker-traefik#258]
I am trying to change my app rules from toml to yml as seen below but i get error and i can no long visit my sites.

time="2022-03-08T12:23:06Z" level=error msg="Unable to obtain ACME certificate for domains \"omv.mydomain.xyz\": unable to generate a certificate for the domains [omv.mydomain.xyz]: error: one or more domains had a problem:\n[omv.mydomain.xyz] [omv.mydomain.xyz] acme: error presenting token: cloudflare: failed to find zone xyz.: zone could not be found\n" providerName=dns-cloudflare.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=omv-rtr@file rule="Host(`omv.mydomain.xyz`)"

app-omv.toml -  Currently been working 

```
[http.routers]
  [http.routers.omv-rtr]
      entryPoints = ["https"]
      rule = "Host(`omv.mydomain.xyz`)"
      service = "omv-svc"
      middlewares = ["chain-no-auth@file"]
      [http.routers.omv-rtr.tls]
        certresolver = "dns-cloudflare"

#[http.middlewares]
#  [http.middlewares.unifi-add-admin.addPrefix]
#    prefix = "/"

[http.services]
  [http.services.omv-svc]
    [http.services.omv-svc.loadBalancer]
      passHostHeader = true
      [[http.services.omv-svc.loadBalancer.servers]]
        url = "http://192.168.1.104:81" # or whatever your external host's IP:port is
```

app-omv.yml 

```
http:
  routers:
    omv-rtr:
      rule: "Host(`omv.mydomain.xyz`)" 
      entryPoints:
        - https
      middlewares:
        - chain-no-auth
      service: omv-svc
      tls:
        certResolver: dns-cloudflare
  services:
    omv-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.104:81"  # or whatever your external host's IP:port is 
```
