### ISSUE TITLE
metube works fine?

### ISSUE THREAD

**Issue by bad1dea** [htpcBeginner/docker-traefik#264]
Read your commit logs, saying you could not get metube to work.. it works fine

Looks like you may be missing.. the network tag..

```
  # MeTube - Youtube downloader
  # Could not get this to work - "Could not resolve name" error
  metube:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: alexta69/metube
    container_name: metube
    user: $PUID:$PGID
    networks:
      - traefik2_proxy
    ports:
       - "8181:8080"
    volumes:
      - $DATADIR/downloads/youtube:/downloads
      - $DOCKERDIR/appdata/metube/config:/config
      - $DOCKERDIR/appdata/metube/cookies:/cookies
    environment:
      - STATE_DIR=/config
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}      
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.metube-rtr.entrypoints=https"
      - "traefik.http.routers.metube-rtr.rule=Host(`metube.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.metube-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"
```
