### ISSUE TITLE
[SOLVED] Accessing Glances data

### ISSUE THREAD

**Issue by Krrost** [htpcBeginner/docker-traefik#266]
Hi I have a problem with hostnames.
I installed Glances and Dashy and all is working fine, then i tried to add Glances widgets but it fails to fetch the datas.
In dashy the widgets are configurated like this:
```
sections:
  - name: CPU Usage
    icon: fas fa-tachometer
    displayData:
      rows: 2
    widgets:
      - type: gl-current-cpu
        options:
          hostname: http://glances:61208
        id: 0_765_glcurrentcpu
      - type: gl-current-cores
        options:
          hostname: http://192.168.90.5:61208
        id: 1_765_glcurrentcores
```
None of the two hostname is able to fetch the data.
I pinged the glances container inside the dashy container and all seems fine, it pinged 192.168.90.5 correctly.
What can cause this?

My setup is identical to the [docker-compose-t2.yml](https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml#L1041)

Thanks

EDIT: Dashy problem. Adding `useProxy: true` in the options worked, with http://glances:61208 hostname. This way:
```
widgets:
      - type: gl-current-cpu
        options:
          hostname: http://glances:61208
          useProxy: true
```
