### ISSUE TITLE
env in rule.yml

### ISSUE THREAD

**Issue by ahmaddxb** [htpcBeginner/docker-traefik#278]
![image](https://user-images.githubusercontent.com/43728586/175506140-588599f7-9353-4734-8f62-2eeff9bdfbbc.png)

Before

```
http:
  routers:
    ha-rtr:
      rule: "Host(`ha.{{env "DOMAINNAME0"}}`)"
```

After

```
http:
  routers:
    ha-rtr:
      rule: "Host(`ha.{{env `DOMAINNAME0`}}`)"
```

**Comment by loryncien** [comment]
```yaml
http:
  routers:
    ha-rtr:
      rule: 'Host(`ha.{{env "DOMAINNAME0"}}`)'
```
