### ISSUE TITLE
📈 Statping Update, Bulk Import Services

### ISSUE THREAD

**Issue by hunterlong** [htpcBeginner/docker-traefik#28]
I love this monster docker-compose, it's awesome to check out, and it's using my software, [Statping](https://github.com/statping/statping) to monitor services. There's a couple updates since @htpcBeginner first added Statping. 

1. **Docker image has changed**, use [statping/statping](https://hub.docker.com/repository/docker/statping/statping) now, rather than ~hunterlong/statping~.
2. Automatically add all services with [Bulk Import](https://github.com/statping/statping/wiki/Bulk-Import-Services)! Would be awesome to see!

---
### Bulk Import Services

I'd definitely do a PR if you'd allow it, pretty simple changes. Basically, the `service.yml` bulk import file would look like:

```yaml
x-check60seconds: &check60seconds
  check_interval: 60
  timeout: 15
  allow_notifications: true
  expected_status: 200
  notify_after: 0
  notify_all_changes: true
  public: true
  redirect: true

services:

  - name: traefik
    type: tcp
    domain: traefik
    <<: *check60seconds

  - name: portainer
    type: tcp
    domain: portainer
    port: 9000
    <<: *check60seconds

  - name: organizr
    type: tcp
    domain: organizr
    port: 80
    <<: *check60seconds
```

Let me know if you think I could submit a PR for this. 💃
