### ISSUE TITLE
Home-Assistant Core: Network Mode

### ISSUE THREAD

**Issue by beloso** [htpcBeginner/docker-traefik#49]
So I am trying to setup my media server, with Home-Assistant. I've passed myself on what is currently on the repo. However, following this approach the container cannot see my devices.

If I use the `network_mode: host`, then Traefik can't forward the container to the exterior.

```
  # Home Assistant Core - Home Automation
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:stable
    networks:
      - t2_proxy
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - target: 8123
        published: $HOMEASSISTANT_PORT
        protocol: tcp
        mode: host
    privileged: true
    volumes:
      - ${USERDIR}/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homeassistant-rtr.entrypoints=https"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`home.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123"
```

Has anyone faced this issue? How did you solve it?
