### ISSUE TITLE
error: unable to find the IP address for the container

### ISSUE THREAD

**Issue by Derever** [htpcBeginner/docker-traefik#60]
With Authelia enabled Traefik logs error:

level=error msg=**"service \"authelia-svc\" error: unable to find the IP address for the container \"/authelia\"**: **the server is ignored"** container=authelia-docker-3f24a3b8732bf2b77fbe2acd8240fc029e28483eac03aa9d0ff91fd83abbfb37 providerName=docker

Any Solutions?

**Comment by Derever** [comment]
There was a wrong config entry on my side which resulted in Authelia not starting up correctly... should be fixed now.

**Comment by ArneAnka** [comment]
How does your config look like? Im having issues to get authelia up-and-runnig. @Derever

**Comment by Derever** [comment]
The Problem was the part:

```
notifier:
  filesystem:
    filename: /config/notification.txt
```
Which i hadn't configured so with that set authelia started without Problems.
Here the full config:

```
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: warn

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# I used this site to generate the secret: https://www.grc.com/passwords.htm
jwt_secret: YOUR-SECRET

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.YOUR_DOMAIN.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
#duo_api:
#  hostname: api-123456789.YOUR_DOMAIN.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.YOUR_DOMAIN.com
      policy: bypass
#    - domain: radarr.YOUR_DOMAIN.com
#      policy: bypass
#      subject: "group:admins"
#      resources:
#      - "^/api/.*$"
    - domain: "*.YOUR_DOMAIN.com"
      policy: one_factor
#    - domain: "*.YOUR_DOMAIN.com"
#      policy: two_factor
    - domain: "YOUR_DOMAIN.com"
      policy: one_factor


session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  secret: YOUR-SECRET
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: YOUR_DOMAIN.com # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
#  redis:
#    host: redis
#    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
# For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
  local:
    path: /config/db.sqlite3
#  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
#    host: MYSQL_HOST
#    port: 3306
#    database: authelia
#    username: DBUSERNAME
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
#    password: DBPASSWORD

notifier:
  filesystem:
    filename: /config/notification.txt
```
