### ISSUE TITLE
Can't Connect to unifi controller or any other only https accesible host

### ISSUE THREAD

**Issue by modparts** [htpcBeginner/docker-traefik#64]
I made this app-unifi.toml to connect to my unifi cloudkey but it doesn't work

[http.routers]
  [http.routers.unifi-rtr]
      entryPoints = ["https"]
      rule = "Host(`unifi.modparts.online`)"
      service = "unifi-svc"
      middlewares = ["chain-basic-auth"]
      [http.routers.unifi-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.unifi-svc]
    [http.services.unifi-svc.loadBalancer]
      passHostHeader = true
      [[http.services.unifi-svc.loadBalancer.servers]]
        url = "https://10.1.0.2:8443" # or whatever your external host's IP:port is

**Comment by modem7** [comment]
Follow this method instead of using an http router: https://www.smarthomebeginner.com/traefik-2-docker-tutorial/#Why_did_I_include_NextCloud_as_an_Example

**Comment by robflate** [comment]
I got unifi working with the following, taken from the repository. I'm not sure why you have to have traefik labels AND a rule file but I don't know enough about this stuff to know the reason. Also, both have a `chain-authelia` middleware but no auth is actually used. I assume because the rule file uses a tcp router which I don't think you can use auth with (?).

I'd love to know how to put unifi behind auth if anyone has any clues. Also, if it's possible with just traefik labels without the rule file.

**docker-compose.yml**
```
unifi:
    container_name: unifi
    image: jacobalberty/unifi:stable
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "6789:6789"
    volumes:
      - $CONFIG/unifi:/unifi
    environment:
      UNIFI_UID: $PUID
      UNIFI_GID: $PGID
      TZ: $TZ
      RUNAS_UID0: "false"
      BIND_PRIV: "false"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.unifi-rtr.entrypoints=https"
      - "traefik.http.routers.unifi-rtr.rule=HostHeader(`unifi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.unifi-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.unifi-rtr.service=unifi-svc"
      - "traefik.http.services.unifi-svc.loadbalancer.server.port=8443"
```

**app-unifi.yml**
```
tcp:
  routers:
    unifi-rtr:
      rule: "HostSNI(`unifi.example.com`)" # will only work with cloudflare Full SSL (not Strict)
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      service: unifi-svc
      tls:
        certResolver: dns-cloudflare
        passthrough: true
  services:
    unifi-svc:
      loadBalancer:
        servers:
          - address: "192.168.0.5:8443"
```

**Cloudflare Page Rule**
```
*unifi.example.com/*
SSL: Full
```
