### ISSUE TITLE
toml => yml

### ISSUE THREAD

**Issue by wardwygaerts** [htpcBeginner/docker-traefik#83]
I have some services wich I defined in toml files. Now I wanted to convert these to yml, should be easy... But when I use the yml file, I get "Internal Server Error". My middlewares are already in yml format and working.

.toml

```
[http.routers]
  [http.routers.docs-rtr]
      entryPoints = ["https"]
      rule = "Host(`docs.test.com`)"
      service = "docs-svc"
      middlewares = ["chain-oauth"]
      [http.routers.docs-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.docs-svc]
    [http.services.docs-svc.loadBalancer]
      passHostHeader = true
      [[http.services.docs-svc.loadBalancer.servers]]
        url = "http://192.168.0.4:32781"
```

.yml
```
http:
  routers:
    docs-rtr:
      rule: "Host(`docs.test.com`)"
      entryPoints:
        - https
      middlewares:
        - chain-oauth
      service: docs-svc
      tls:
        certResolver: dns-cloudflare
  services:
    docs-svc:
      loadBalancer:
        servers:
          - address: "http://192.168.0.4:32781"
```

What am I missing?
