### ISSUE TITLE
Issues with middleware chains after upgrading to Traefik 2.3 Picodon

### ISSUE THREAD

**Issue by tehniemer** [htpcBeginner/docker-traefik#89]
I'm having a problem with traefik not finding the middlewares-chains in the file that was working successfully with traefik 2.2 chevrotin, I'm seeing errors like those below and the sites won't resolve. I've changed nothing other than the version of traefik.

```
level=error msg="middleware \"chain-authelia@file\" does not exist" entryPointName=https routerName=hydra-rtr@docker
```

and my traefik compose file
```
  traefik:
    image: traefik:chevrotin  #the chevrotin tag refers to v2.2.x, picodon refers to v2.3.x 
    container_name: traefik
    restart: always
    command: #CLI arguments
      - '--global.checkNewVersion=true'
      - '--global.sendAnonymousUsage=true'
      - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - '--entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22'
      - '--entryPoints.traefik.address=:8080'
      - '--api=true'
      # - '--api.insecure=true'
      # - '--serversTransport.insecureSkipVerify=true'
      - '--log=true'
      - '--log.level=WARN' # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - '--accessLog=true'
      - '--accessLog.filePath=/traefik.log'
      - '--accessLog.bufferingSize=100' # Configuring a buffer of 100 lines
      - '--accessLog.filters.statusCodes=400-499'
      - '--providers.docker=true'
      # - '--providers.docker.endpoint=unix:///var/run/docker.sock' # Use Docker Socket Proxy instead for improved security
      - '--providers.docker.endpoint=tcp://socket-proxy:2375'
      # - '--providers.docker.defaultrule=Host(`{{ index .Labels 'com.docker.compose.service' }}.$DOMAINNAME`)'
      - '--providers.docker.exposedByDefault=false'
      # - '--entrypoints.https.http.middlewares=chain-authelia@file'
      - '--entrypoints.https.http.tls.options=tls-opts@file'
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - '--entrypoints.https.http.tls.certresolver=dns-cloudflare'
      - '--entrypoints.https.http.tls.domains[0].main=$DOMAINNAME'
      - '--entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME'
      # - '--entrypoints.https.http.tls.domains[1].main=$DOMAIN' # Pulls main cert for second domain
      # - '--entrypoints.https.http.tls.domains[1].sans=*.$DOMAIN' # Pulls wildcard cert for second domain
      - '--providers.docker.network=proxy'
      - '--providers.docker.swarmMode=false'
      - '--providers.file.directory=/rules' # Load dynamic configuration from one or more .toml or .yml files in a directory
      # - '--providers.file.filename=/path/to/file # Load dynamic configuration from a file
      - '--providers.file.watch=true' # Only works on top level files in the rules folder
      # - '--certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory' # LetsEncrypt Staging Server - uncomment when testing
      - '--certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL'
      - '--certificatesResolvers.dns-cloudflare.acme.storage=/acme.json'
      - '--certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare'
      - '--certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53'
      - '--certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90' # To delay DNS check and reduce LE hitrate
    networks:
      - proxy
      - socket_proxy
    depends_on:
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$DOCKER_DIR/traefik2/rules:/rules' # file provider directory
      - '$DOCKER_DIR/traefik2/acme/acme.json:/acme.json' # cert location - you must touch this file and change permissions to 600
      - '$DOCKER_DIR/traefik2/traefik.log:/traefik.log' # for fail2ban - make sure to touch file before starting container
    environment:
      CF_API_EMAIL: $CLOUDFLARE_EMAIL
      CF_API_KEY: $CLOUDFLARE_API_KEY
    labels:
      - 'traefik.enable=true'
      ## HTTP-to-HTTPS Redirect
      - 'traefik.http.routers.http-catchall.entrypoints=http'
      - 'traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      ## HTTP Routers
      - 'traefik.http.routers.traefik-rtr.entrypoints=https'
      - 'traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)'
      ## Services - API
      - 'traefik.http.routers.traefik-rtr.service=api@internal'
      ## Middlewares
      - 'traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file'
```
