### ISSUE TITLE
YML Static Config Question

### ISSUE THREAD

**Issue by undaunt** [htpcBeginner/docker-traefik#92]
Hey, just wondering the proper syntax for calling the tls-opts.yml file if I were using a .yml static config instead of the environmental variables. I've got the rest of the yml file figured out with the examples on the traefik docs, but cannot locate an example for this.

Or, similarly, how can I test that the tls options are in effect properly? Then I can try various syntax choices on my own and vet out which one is correct.

Thanks! Current sanitized traefik.yml:

```
# Static Configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: WARN

accessLog:
  filePath: "/traefik.log"
  bufferingSize: 100
  filters:
    statusCodes: # Show client error type codes
      - "400-499"

api:
  dashboard: true

pilot:
  token: "xxxxxxxxxxxxxxxxxxxx"

entryPoints:
  http:
    address: ":80"
    http:
      redirections: # global redirect, remove and set at router level if needed
        entrypoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        options: "/rules/tls-opts.yml"
        certResolver: cloudflare-dns
        domains:
          - main: "xxxxxxxxxxxx"
            sans:
              - "*.xxxxxxxxxxxx"
    forwardedHeaders:
      trustedIPs: # trust cloudflare IPs to forward origin IPs
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/12"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\" }}.$DOMAINNAME`)"
    exposedByDefault: false
    network: traefik-proxy
  file:
   directory: "/rules"
   watch: true

certificatesResolvers:
  cloudflare-dns:
    acme:
      email: "xxxxxxxxxxxx"
      storage: "/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 90
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

```
